---
title: "Capstone Project v1"
author: "H Karen Tam"
date: "October 18, 2017"
output:
  html_document: default
---

```{r}

# Load tidyr
suppressMessages(library(tidyr))

# Load dplyr
suppressMessages(library(dplyr))

# Load ggplot2
suppressMessages(library(ggplot2))

# Load readxl - read excel files
library(readxl)

# Import excel files
income_pp <- read_excel("income_pp.xlsx")
life_expectancy <- read_excel("life_expectancy.xlsx")
total_health_spending_pp <- read_excel("total_health_spending_pp.xlsx")
government_health_spending_pp <- read_excel("government_health_spending_pp.xlsx")
breast_cancer_death <- read_excel("breast_cancer_death.xlsx")
cervical_cancer_death <- read_excel("cervical_cancer_death.xlsx")
liver_cancer_death_male <- read_excel("liver_cancer_death_male.xlsx")
liver_cancer_death_female <- read_excel("liver_cancer_death_female.xlsx")
lung_cancer_death_male <- read_excel("lung_cancer_death_male.xlsx")
lung_cancer_death_female <- read_excel("lung_cancer_death_female.xlsx")
prostate_cancer_death <- read_excel("prostate_cancer_death.xlsx")
stomach_cancer_death_male <- read_excel("stomach_cancer_death_male.xlsx")
stomach_cancer_death_female <- read_excel("stomach_cancer_death_female.xlsx")
food_supply <- read_excel("food_supply.xlsx")
improved_drinking_water <- read_excel("improved_drinking_water.xlsx")

```
```{r}

# Reshape income_pp. Make values of different years as rows. 
income_pp_year_as_row <- gather(income_pp, "Year", "Income_per_person", 2:53, na.rm = FALSE)

# Print income_pp_year_as_row
# income_pp_year_as_row

# change income_per_person's value as numberic 
as.numeric(income_pp_year_as_row$Income_per_person)

# Round up values in Income_per_person column to 2 decimal places
# round(income_pp_year_as_row$Income_per_person, 2)

# Show the mean of GDP per capita of each country from 1960 to 2011
paste("The Mean of Income Per Person(GDP Per Capita) By Country from 1960 to 2011")
income_pp_year_as_row %>% 
  group_by(Country) %>% 
  summarise(mean=mean(Income_per_person, na.rm = TRUE), count=sum(!is.na(Income_per_person))) %>%
  arrange(desc(mean))
  
```

```{r}

# Show basic descriptive statistics
summary(income_pp_year_as_row)

# Standard Deviation of Income Per Person
ipp_sd <- round(sd(income_pp_year_as_row$Income_per_person, na.rm = TRUE), 2)
paste("The Standard Deviation of GDP Per Capita is", ipp_sd,".")
  
```


```{r}

# Histogram showing income per person in different countries

hist(income_pp$`2010`, xlab="GDP Per Capita 2010", main="Income In Different Countries in 2010")

hist(income_pp$`2000`, xlab="GDP Per Capita 2000", main="Income In Different Countries in 2000")

hist(income_pp$`1990`, xlab="GDP Per Capita 1990", main="Income In Different Countries in 1990")

hist(income_pp$`1980`, xlab="GDP Per Capita 1980", main="Income In Different Countries in 1980")

hist(income_pp$`1970`, xlab="GDP Per Capita 1970", main="Income In Different Countries in 1970")

hist(income_pp$`1960`, xlab="GDP Per Capita 1960", main="Income In Different Countries in 1960")

```

```{r}
# Check to see the outliers are resasonable.

subset(income_pp_year_as_row, Income_per_person > 50000)

```

```{r}

# Reshape life_expectancy. Make values of different years as rows. 
life_expectancy_year_as_row <- gather(life_expectancy, "Year", "Life_Expectancy", 2:58, na.rm = FALSE)

# Print life_expectancy_year_as_row
# life_expectancy_year_as_row

# change Life_Expectancy's value as numberic 
as.numeric(life_expectancy_year_as_row$Life_Expectancy)

# Show the mean of life expectancy at birth by year of each country from 1960 to 2016
paste("The Mean of Life Expectancy at Birth (Year) By Country from 1960 to 2016")
life_expectancy_year_as_row %>% 
  group_by(Country) %>% 
  summarise(mean=mean(Life_Expectancy, na.rm = TRUE), count=sum(!is.na(Life_Expectancy))) %>%
  arrange(desc(mean))

```

```{r}

# Show basic descriptive statistics
summary(life_expectancy_year_as_row)

# Standard Deviation of Life Expectancy
ipp_sd <- round(sd(life_expectancy_year_as_row$Life_Expectancy, na.rm = TRUE), 2)
paste("The Standard Deviation of Life Expectancy is", ipp_sd, "years")
  
```


```{r}

# Histogram showing life expectancy in different countries

hist(life_expectancy$`2016`, xlab="Life Expectancy 2016", main="Life Expectancy In Different Countries in 2016")

hist(life_expectancy$`2010`, xlab="Life Expectancy 2010", main="Life Expectancy In Different Countries in 2010")

hist(life_expectancy$`2000`, xlab="Life Expectancy 2000", main="Life Expectancy In Different Countries in 2000")

hist(life_expectancy$`1990`, xlab="Life Expectancy 1990", main="Life Expectancy In Different Countries in 1990")

hist(life_expectancy$`1980`, xlab="Life Expectancy 1980", main="Life Expectancy In Different Countries in 1980")

hist(life_expectancy$`1970`, xlab="Life Expectancy 1970", main="Life Expectancy In Different Countries in 1970")

hist(life_expectancy$`1960`, xlab="Life Expectancy 1960", main="Life Expectancy In Different Countries in 1960")

```

```{r}

# Check values of life expectancy under 30 years old.

# There are 9 records in this subset. The numbers are from Mali in 1960 and 1961, Cambodia from 1975 to 1980, and Rwanda in 1994. The short lives can be explained by wars in these countries in the stated years. 

subset(life_expectancy_year_as_row, Life_Expectancy < 30)

```

```{r}

# Reshape total_health_spending_pp. Make values of different years as rows. 
total_health_spending_pp_year_as_row <- gather(total_health_spending_pp, "Year", "Total_Health_Spending_Per_Person", 2:17, na.rm = FALSE)

# Print total_health_spending_pp_year_as_row
# total_health_spending_pp_year_as_row

# change Total Health Spending's value as numberic 
as.numeric(total_health_spending_pp_year_as_row$Total_Health_Spending_Per_Person)

# Show the mean of total health spending in US$ of each country from 1995 to 2010
paste("The Mean of Total Health Spending in US$ By Country from 1995 to 2010")
total_health_spending_pp_year_as_row %>% 
  group_by(Country) %>% 
  summarise(mean=mean(Total_Health_Spending_Per_Person, na.rm = TRUE), count=sum(!is.na(Total_Health_Spending_Per_Person))) %>%
  arrange(desc(mean))

```

```{r}

# Show basic descriptive statistics
summary(total_health_spending_pp_year_as_row)

# Standard Deviation of Total Health Spending Per Person
ipp_sd <- round(sd(total_health_spending_pp_year_as_row$Total_Health_Spending_Per_Person, na.rm = TRUE), 2)
paste("The Standard Deviation of Total Health Spending is $", ipp_sd, "US Dollars per person.")
  
```


```{r}

# Histogram showing total health spending in different countries

hist(total_health_spending_pp$`2010`, xlab="Total Health Spending Per Person in US Dollar in 2010", main="Total Health Spending In Different Countries in 2010")

hist(total_health_spending_pp$`2005`, xlab="Total Health Spending Per Person in US Dollar in 2005", main="Total Health Spending In Different Countries in 2005")

hist(total_health_spending_pp$`2000`, xlab="Total Health Spending Per Person in US Dollar in 2000", main="Total Health Spending In Different Countries in 2000")

hist(total_health_spending_pp$`1995`, xlab="Total Health Spending Per Person in US Dollar in 1995", main="Total Health Spending In Different Countries in 1995")

```

```{r}
# Check the outliers to see whether they are reasonable.

# There are 6 records in this subset. The countries are Luxembourg, Norway, and United States from 2008 to 2010. These are rich countries, and the numbers seem to be reasonable.

subset(total_health_spending_pp_year_as_row, Total_Health_Spending_Per_Person > 8000)

```

```{r}

# Reshape government_health_spending_pp. Make values of different years as rows. 
government_health_spending_pp_year_as_row <- gather(government_health_spending_pp, "Year", "Government_Health_Spending_Per_Person", 2:17, na.rm = FALSE)

# Print government_health_spending_pp_year_as_row
# government_health_spending_pp_year_as_row

# change Total Health Spending's value as numberic 
as.numeric(government_health_spending_pp_year_as_row$Government_Health_Spending_Per_Person)

# Show the mean of government health spending in US$ of each country from 1995 to 2010
paste("The Mean of Government Health Spending in US$ By Country from 1995 to 2010")
government_health_spending_pp_year_as_row %>% 
  group_by(Country) %>% 
  summarise(mean=mean(Government_Health_Spending_Per_Person, na.rm = TRUE), count=sum(!is.na(Government_Health_Spending_Per_Person))) %>%
  arrange(desc(mean))

```


```{r}

# Show basic descriptive statistics
summary(government_health_spending_pp_year_as_row)

# Standard Deviation of Total Health Spending Per Person
ipp_sd <- round(sd(government_health_spending_pp_year_as_row$Government_Health_Spending_Per_Person, na.rm = TRUE), 2)
paste("The Standard Deviation of Government Health Spending is $", ipp_sd, "US Dollars per person.")
  
```


```{r}

# Histogram showing government health spending in different countries

hist(government_health_spending_pp$`2010`, xlab="Government Health Spending Per Person in US Dollar in 2010", main="Government Health Spending In Different Countries in 2010")

hist(government_health_spending_pp$`2005`, xlab="Government Health Spending Per Person in US Dollar in 2005", main="Government Health Spending In Different Countries in 2005")

hist(government_health_spending_pp$`2000`, xlab="Government Health Spending Per Person in US Dollar in 2000", main="Government Health Spending In Different Countries in 2000")

hist(government_health_spending_pp$`1995`, xlab="Government Health Spending Per Person in US Dollar in 1995", main="Government Health Spending In Different Countries in 1995")

```

```{r}

# Check the outliers of Government Health Spending Per Person
# There are 8 records of numbers higher than US$6,000. These numbers are from Luxembourg and Norway from 2007 to 2010. The numbers should be reasonable.

subset(government_health_spending_pp_year_as_row, Government_Health_Spending_Per_Person > 6000)

```

```{r}

# Reshape food_supply. Make values of different years as rows. 
food_supply_year_as_row <- gather(food_supply, "Year", "Food_Supply", 2:48, na.rm = FALSE)

# Print food_supply_year_as_row
# food_supply_year_as_row

# change food_supply's value as numberic 
as.numeric(food_supply_year_as_row$Food_Supply)

# Show the mean of food supply in KCal per person per day in  each country from 1961 to 2007
paste("The Mean of Food Supply in KCal Per Person Per Day By Country From 1961 to 2007")
food_supply_year_as_row %>% 
  group_by(Country) %>% 
  summarise(mean=mean(Food_Supply, na.rm = TRUE), count=sum(!is.na(Food_Supply))) %>%
  arrange(desc(mean))

```


```{r}

# Show basic descriptive statistics
summary(food_supply_year_as_row)

# Standard Deviation of Food Supply
ipp_sd <- round(sd(food_supply_year_as_row$Food_Supply, na.rm = TRUE), 2)
paste("The Standard Deviation of Food Supply is", ipp_sd, "Calories per person per day.")
  
```

```{r}

# Histogram showing food supply in different countries

hist(food_supply$`2007`, xlab="Food Supply in Calories Per Person Per Day in 2007", main="Food Supply In Different Countries in 2007")

hist(food_supply$`1985`, xlab="Food Supply in Calories Per Person Per Day in 1985", main="Food Supply In Different Countries in 1985")

hist(food_supply$`1961`, xlab="Food Supply in Calories Per Person Per Day in 1961", main="Food Supply In Different Countries in 1961")

```

```{r}
# Check the outliers to see whether they are reasonable.

# (change) There are 3 records in this subset. The only country wiht mor ethan 3800 KCal per person per day is Austria in 2000s. 

subset(food_supply_year_as_row, Food_Supply > 3800)

```

```{r}

# Reshape improved_drinking_water. Make values of different years as rows. 
improved_drinking_water_year_as_row <- gather(improved_drinking_water, "Year", "Improved_Water", 2:22, na.rm = FALSE)

# Print improved_drinking_water_year_as_row
# improved_drinking_water_year_as_row

# change Improved drinking water's value as numberic 
as.numeric(improved_drinking_water_year_as_row$Improved_Water)

# Show the mean of the percentage of the total population using improved drinking water sources from 1990 to 2010
paste("The Mean of the Percentage of the Population Using Improved Drinking Water Sources By Country From 1990 to 2010")
improved_drinking_water_year_as_row %>% 
  group_by(Country) %>% 
  summarise(mean=mean(Improved_Water, na.rm = TRUE), count=sum(!is.na(Improved_Water))) %>%
  arrange(desc(mean))

```


```{r}

# Show basic descriptive statistics
summary(improved_drinking_water_year_as_row)

# Standard Deviation of Improved Drinking Water
ipp_sd <- round(sd(improved_drinking_water_year_as_row$Improved_Water, na.rm = TRUE), 2)
paste("The Standard Deviation of the Percentage of the Population Using Improved Drinking Water Sources is", ipp_sd, ".")
  
```

```{r}

# Histogram showing improved drinking water in different countries

hist(improved_drinking_water$`1990`, xlab="Percentage of the Population Using Improved Drinking Water Sources in 1990", main="Using Improved Drinking Water Sources In Different Countries in 1990")

hist(improved_drinking_water$`2010`, xlab="Percentage of the Population Using Improved Drinking Water Sources in 2010", main="Using Improved Drinking Water Sources In Different Countries in 2010")

```

```{r}
# Check the outliers to see whether they are reasonable.

# There are 6 records in this subset. The only country with less than 10% of the population to have access to improved drinking water sources is Afghanistan in 1990s. 

subset(improved_drinking_water_year_as_row, Improved_Water < 10)

```

```{r} 

# Reshape breast_cancer_death. Make values of different years as rows. 
breast_cancer_death_year_as_row <- gather(breast_cancer_death, "Year", "Breast_Cancer_Death", 2:54, na.rm = FALSE)

# Print breast_cancer_death_year_as_row
# breast_cancer_death_year_as_row

# change breast cacner death's value as numberic 
as.numeric(breast_cancer_death_year_as_row$Breast_Cancer_Death)

# Show the mean of breast cancer deaths per 100,000 female of each country from 1950 to 2002
paste("The Mean of Breast Cancer Deaths Per 100,000 Female By Country from 1950 to 2002")
breast_cancer_death_year_as_row %>% 
  group_by(Country) %>% 
  summarise(mean=mean(Breast_Cancer_Death, na.rm = TRUE), count=sum(!is.na(Breast_Cancer_Death))) %>%
  arrange(desc(mean))

```

```{r}

# Show basic descriptive statistics
summary(breast_cancer_death_year_as_row)

# Standard Deviation of breast cancer deaths per 100,000 female
ipp_sd <- round(sd(breast_cancer_death_year_as_row$Breast_Cancer_Death, na.rm = TRUE), 2)
paste("The Standard Deviation of Breast Cancer Deaths per 100,000 female is ", ipp_sd, ".")

```

```{r}

# Histogram showing breast cancer deaths in different countries

hist(breast_cancer_death$`1987`, xlab="Breast Cancer Deaths Per 100,000 Female 1987", main="Breast Cancer Deaths In Different Countries in 1987")
hist(breast_cancer_death$`1992`, xlab="Breast Cancer Deaths Per 100,000 Female 1992", main="Breast Cancer Deaths In Different Countries in 1992")
hist(breast_cancer_death$`1997`, xlab="Breast Cancer Deaths Per 100,000 Female 1997", main="Breast Cancer Deaths In Different Countries in 1997")
hist(breast_cancer_death$`2002`, xlab="Breast Cancer Deaths Per 100,000 Female 2002", main="Breast Cancer Deaths In Different Countries in 2002")


```

```{r}

# Check the outliers to see whether they are reasonable.

# There are a total of 12 records shown in this subset. The countries are Iceland, Ireland, and Malta. In 1951, Iceland had highest number of breast cancer death since 1950. It is reasonable because its numbers are relatively high in other years. 

subset(breast_cancer_death_year_as_row, Breast_Cancer_Death > 30)

```

```{r} 

# Reshape cervical_cancer_death. Make values of different years as rows. 
cervical_cancer_death_year_as_row <- gather(cervical_cancer_death, "Year", "Cervical_Cancer_Death", 2:54, na.rm = FALSE)

# Print cervical_cancer_death_year_as_row
# cervical_cancer_death_year_as_row

# Change cervical cancer death's value as numberic 
as.numeric(cervical_cancer_death_year_as_row$Cervical_Cancer_Death)

# Show the mean of cervical cancer deaths per 100,000 female of each country from 1950 to 2002
paste("The Mean of Cervical Cancer Deaths Per 100,000 Female By Country from 1950 to 2002")
cervical_cancer_death_year_as_row %>% 
  group_by(Country) %>% 
  summarise(mean=mean(Cervical_Cancer_Death, na.rm = TRUE), count=sum(!is.na(Cervical_Cancer_Death))) %>%
  arrange(desc(mean))

```

```{r}

# Show basic descriptive statistics
summary(cervical_cancer_death_year_as_row)

# Standard Deviation of cervical cancer deaths per 100,000 female
ipp_sd <- round(sd(cervical_cancer_death_year_as_row$Cervical_Cancer_Death, na.rm = TRUE), 2)
paste("The Standard Deviation of Cervical Cancer Deaths Per 100,000 Female is ", ipp_sd, ".")

```

```{r}

# Histogram showing cervical cancer deaths in different countries

hist(cervical_cancer_death$`1987`, xlab="Cervical Cancer Deaths Per 100,000 Female 1987", main="Cervical Cancer Deaths In Different Countries in 1987")
hist(cervical_cancer_death$`1992`, xlab="Cervical Cancer Deaths Per 100,000 Female 1992", main="Cervical Cancer Deaths In Different Countries in 1992")
hist(cervical_cancer_death$`1997`, xlab="Cervical Cancer Deaths Per 100,000 Female 1997", main="Cervical Cancer Deaths In Different Countries in 1997")
hist(cervical_cancer_death$`2002`, xlab="Cervical Cancer Deaths Per 100,000 Female 2002", main="Cervical Cancer Deaths In Different Countries in 2002")
  
```

```{r}

# Check the outliers to see whether they are reasonable.

# There are a total of 8 records shown in this subset. All outliers are from year 2002. It is reasonable because 2012 numbers are relatively higher than other years. 

subset(cervical_cancer_death_year_as_row, Cervical_Cancer_Death > 40)


```

```{r} 

# Reshape liver_cancer_death_male. Make values of different years as rows. 
liver_cancer_death_male_year_as_row <- gather(liver_cancer_death_male, "Year", "Liver_Cancer_Death_Male", 2:49, na.rm = FALSE)

# Print liver_cancer_death_male_year_as_row
# liver_cancer_death_male_year_as_row

# Change liver cancer death's value as numberic 
as.numeric(liver_cancer_death_male_year_as_row$Liver_Cancer_Death_Male)

# Show the mean of liver cancer deaths per 100,000 male of each country from 1955 to 2002
paste("The Mean of Liver Cancer Deaths Per 100,000 Male By Country from 1955 to 2002")
liver_cancer_death_male_year_as_row %>% 
  group_by(Country) %>% 
  summarise(mean=mean(Liver_Cancer_Death_Male, na.rm = TRUE), count=sum(!is.na(Liver_Cancer_Death_Male))) %>%
  arrange(desc(mean))

```

```{r} 

# Reshape liver_cancer_death_female. Make values of different years as rows. 
liver_cancer_death_female_year_as_row <- gather(liver_cancer_death_female, "Year", "Liver_Cancer_Death_Female", 2:49, na.rm = FALSE)

# Print liver_cancer_death_female_year_as_row
# liver_cancer_death_female_year_as_row

# Change liver cancer death's value as numberic 
as.numeric(liver_cancer_death_female_year_as_row$Liver_Cancer_Death_Female)

# Show the mean of liver cancer deaths per 100,000 female of each country from 1955 to 2002
paste("The Mean of Liver Cancer Deaths Per 100,000 Female By Country from 1955 to 2002")
liver_cancer_death_female_year_as_row %>% 
  group_by(Country) %>% 
  summarise(mean=mean(Liver_Cancer_Death_Female, na.rm = TRUE), count=sum(!is.na(Liver_Cancer_Death_Female))) %>%
  arrange(desc(mean))

```

```{r}

# Join liver_cancer_death_male_year_as_row and liver_cancer_death_female_year_as_row
liver_cancer_death_year_as_row <- inner_join(liver_cancer_death_male_year_as_row, liver_cancer_death_female_year_as_row)

# Add liver cancer death numbers for male and female, create new column, and store the values in liver_cancer_death_year_as_row
liver_cancer_death_year_as_row <- liver_cancer_death_year_as_row %>% 
  mutate(Liver_Cancer_Death = Liver_Cancer_Death_Male + Liver_Cancer_Death_Female)

# Print liver_cancer_death_year_as_row
# liver_cancer_death_year_as_row

# Show the mean of liver cancer deaths per 100,000 person of each country from 1955 to 2002
paste("The Mean of Liver Cancer Deaths Per 100,000 Person By Country from 1955 to 2002")
liver_cancer_death_year_as_row %>% 
  group_by(Country) %>% 
  summarise(mean=mean(Liver_Cancer_Death, na.rm = TRUE), count=sum(!is.na(Liver_Cancer_Death))) %>%
  arrange(desc(mean))

```

```{r}

# Show basic descriptive statistics
summary(liver_cancer_death_year_as_row)

# Standard Deviation of liver cancer deaths per 100,000 person
ipp_sd <- round(sd(liver_cancer_death_year_as_row$Liver_Cancer_Death, na.rm = TRUE), 2)
paste("The Standard Deviation of Liver Cancer Deaths Per 100,000 Person Is ", ipp_sd, ".")

```

```{r}

# Create tables for different years in order to create histograms
liver_cancer_death_1987 <- subset(liver_cancer_death_year_as_row, Year == 1987) 
liver_cancer_death_1992 <- subset(liver_cancer_death_year_as_row, Year == 1992) 
liver_cancer_death_1997 <- subset(liver_cancer_death_year_as_row, Year == 1997) 
liver_cancer_death_2002 <- subset(liver_cancer_death_year_as_row, Year == 2002) 

# Histogram showing liver cancer deaths in different countries

hist(liver_cancer_death_1987$Liver_Cancer_Death, xlab="Liver Cancer Deaths Per 100,000 Person 1987", main="Liver Cancer Deaths In Different Countries in 1987")
hist(liver_cancer_death_1992$Liver_Cancer_Death, xlab="Liver Cancer Deaths Per 100,000 Person 1992", main="Liver Cancer Deaths In Different Countries in 1992")
hist(liver_cancer_death_1997$Liver_Cancer_Death, xlab="Liver Cancer Deaths Per 100,000 Person 1997", main="Liver Cancer Deaths In Different Countries in 1997")
hist(liver_cancer_death_2002$Liver_Cancer_Death, xlab="Liver Cancer Deaths Per 100,000 Person 2002", main="Liver Cancer Deaths In Different Countries in 2002")

```

```{r}

# Check whether the outliers are reasonable.
# Indeed, Mongolia and Mozambique have much higher rate of liver cancer according to online resources. So the outliers should be correct. 

subset(liver_cancer_death_year_as_row, Liver_Cancer_Death > 80)


```

```{r} 

# Reshape lung_cancer_death_male. Make values of different years as rows. 
lung_cancer_death_male_year_as_row <- gather(lung_cancer_death_male, "Year", "Lung_Cancer_Death_Male", 2:54, na.rm = FALSE)

# Print lung_cancer_death_male_year_as_row
# lung_cancer_death_male_year_as_row

# Change lung cancer death's value as numberic 
as.numeric(lung_cancer_death_male_year_as_row$Lung_Cancer_Death_Male)

# Show the mean of lung cancer deaths per 100,000 male of each country from 1950 to 2002
paste("The Mean of Lung Cancer Deaths Per 100,000 Male By Country from 1950 to 2002")
lung_cancer_death_male_year_as_row %>% 
  group_by(Country) %>% 
  summarise(mean=mean(Lung_Cancer_Death_Male, na.rm = TRUE), count=sum(!is.na(Lung_Cancer_Death_Male))) %>%
  arrange(desc(mean))

```

```{r} 

# Reshape lung_cancer_death_female. Make values of different years as rows. 
lung_cancer_death_female_year_as_row <- gather(lung_cancer_death_female, "Year", "Lung_Cancer_Death_Female", 2:54, na.rm = FALSE)

# Print lung_cancer_death_female_year_as_row
# lung_cancer_death_female_year_as_row

# Change lung cancer death's value as numberic 
as.numeric(lung_cancer_death_female_year_as_row$Lung_Cancer_Death_Female)

# Show the mean of lung cancer deaths per 100,000 female of each country from 1950 to 2002
paste("The Mean of Lung Cancer Deaths Per 100,000 Female By Country from 1950 to 2002")
lung_cancer_death_female_year_as_row %>% 
  group_by(Country) %>% 
  summarise(mean=mean(Lung_Cancer_Death_Female, na.rm = TRUE), count=sum(!is.na(Lung_Cancer_Death_Female))) %>%
  arrange(desc(mean))

```

```{r}
# Join lung_cancer_death_male_year_as_row and lung_cancer_death_female_year_as_row
lung_cancer_death_year_as_row <- inner_join(lung_cancer_death_male_year_as_row, lung_cancer_death_female_year_as_row)

# Add lung cancer death numbers for male and female, create new column, and store the values in lung_cancer_death_year_as_row
lung_cancer_death_year_as_row <- lung_cancer_death_year_as_row %>% 
  mutate(Lung_Cancer_Death = Lung_Cancer_Death_Male + Lung_Cancer_Death_Female)

# Print lung_cancer_death_year_as_row
# lung_cancer_death_year_as_row

# Show the mean of lung cancer deaths per 100,000 person of each country from 1950 to 2002
paste("The Mean of Lung Cancer Deaths Per 100,000 Person By Country from 1950 to 2002")
lung_cancer_death_year_as_row %>% 
  group_by(Country) %>% 
  summarise(mean=mean(Lung_Cancer_Death, na.rm = TRUE), count=sum(!is.na(Lung_Cancer_Death))) %>%
  arrange(desc(mean))
```

```{r}

# Show basic descriptive statistics
summary(lung_cancer_death_year_as_row)

# Standard Deviation of lung cancer death per 100,000 persons
ipp_sd <- round(sd(lung_cancer_death_year_as_row$Lung_Cancer_Death, na.rm = TRUE), 2)
paste("The Standard Deviation of Lung Cancer Deaths Per 100,000 Person Is ", ipp_sd, ".")

```

```{r}

# Create tables for different years in order to create histograms

lung_cancer_death_1987 <- subset(lung_cancer_death_year_as_row, Year == 1987) 
lung_cancer_death_1992 <- subset(lung_cancer_death_year_as_row, Year == 1992) 
lung_cancer_death_1997 <- subset(lung_cancer_death_year_as_row, Year == 1997) 
lung_cancer_death_2002 <- subset(lung_cancer_death_year_as_row, Year == 2002) 

# Histogram showing lung cancer deaths in different countries

hist(lung_cancer_death_1987$Lung_Cancer_Death, xlab="Lung Cancer Deaths Per 100,000 Person 1987", main="Lung Cancer Deaths In Different Countries in 1987")
hist(lung_cancer_death_1992$Lung_Cancer_Death, xlab="Lung Cancer Deaths Per 100,000 Person 1992", main="Lung Cancer Deaths In Different Countries in 1992")
hist(lung_cancer_death_1997$Lung_Cancer_Death, xlab="Lung Cancer Deaths Per 100,000 Person 1997", main="Lung Cancer Deaths In Different Countries in 1997")
hist(lung_cancer_death_2002$Lung_Cancer_Death, xlab="Lung Cancer Deaths Per 100,000 Person 2002", main="Lung Cancer Deaths In Different Countries in 2002")

```

```{r}

# Check whether the outliers are reasonable.
# All outliers are from Hungary from 1993 to 2002. This country has the highest lung cancer rate. The numbers should be correct. 

subset(lung_cancer_death_year_as_row, Lung_Cancer_Death > 100)


```


```{r} 

# Reshape prostate_cancer_death. Make values of different years as rows. 
prostate_cancer_death_year_as_row <- gather(prostate_cancer_death, "Year", "Prostate_Cancer_Death", 2:54, na.rm = FALSE)

# Print prostate_cancer_death_year_as_row
# prostate_cancer_death_year_as_row

# Change prostate cancer death's value as numberic 
as.numeric(prostate_cancer_death_year_as_row$Prostate_Cancer_Death)

# Show the mean of prostate cancer deaths per 100,000 male of each country from 1950 to 2002
paste("The Mean of Prostate Cancer Deaths Per 100,000 Male By Country from 1950 to 2002")
prostate_cancer_death_year_as_row %>% 
  group_by(Country) %>% 
  summarise(mean=mean(Prostate_Cancer_Death, na.rm = TRUE), count=sum(!is.na(Prostate_Cancer_Death))) %>%
  arrange(desc(mean))

```
```{r}

# Show basic descriptive statistics
summary(prostate_cancer_death_year_as_row)

# Standard Deviation of prostate cancer deaths per 100,000 male
ipp_sd <- round(sd(prostate_cancer_death_year_as_row$Prostate_Cancer_Death, na.rm = TRUE), 2)
paste("The Standard Deviation of Prostate Cancer Deaths Per 100,000 Male Is ", ipp_sd, ".")

```

```{r}

# Histogram showing prostate cancer deaths in different countries

hist(prostate_cancer_death$`1987`, xlab="Prostate Cancer Deaths Per 100,000 Male 1987", main="Prostate Cancer Deaths In Different Countries in 1987")

hist(prostate_cancer_death$`1992`, xlab="Prostate Cancer Deaths Per 100,000 Male 1992", main="Prostate Cancer Deaths In Different Countries in 1992")

hist(prostate_cancer_death$`1997`, xlab="Prostate Cancer Deaths Per 100,000 Male 1997", main="Prostate Cancer Deaths In Different Countries in 1997")

hist(prostate_cancer_death$`2002`, xlab="Prostate Cancer Deaths Per 100,000 Male 2002", main="Prostate Cancer Deaths In Different Countries in 2002")
  
```

```{r}

# Check whether the outliers are reasonable.
# There are 9 records in this subset. All outliers are from Barbados, as well as Trinidad and Tobago. These countries indeed have higher prostate cancer rate than other countries. The numbers should be correct. 

subset(prostate_cancer_death_year_as_row, Prostate_Cancer_Death > 50)


```

```{r} 

# Reshape stomach_cancer_death_male. Make values of different years as rows. 
stomach_cancer_death_male_year_as_row <- gather(stomach_cancer_death_male, "Year", "Stomach_Cancer_Death_Male", 2:54, na.rm = FALSE)

# Print stomach_cancer_death_male_year_as_row
# stomach_cancer_death_male_year_as_row

# Change stomach cancer death's value as numberic 
as.numeric(stomach_cancer_death_male_year_as_row$Stomach_Cancer_Death_Male)

# Show the mean of stomach cancer deaths per 100,000 male of each country from 1950 to 2002
paste("The Mean of Stomach Cancer Deaths Per 100,000 Male By Country from 1950 to 2002")
stomach_cancer_death_male_year_as_row %>% 
  group_by(Country) %>% 
  summarise(mean=mean(Stomach_Cancer_Death_Male, na.rm = TRUE), count=sum(!is.na(Stomach_Cancer_Death_Male))) %>%
  arrange(desc(mean))

```

```{r}

# Reshape stomach_cancer_death_female. Make values of different years as rows. 
stomach_cancer_death_female_year_as_row <- gather(stomach_cancer_death_female, "Year", "Stomach_Cancer_Death_Female", 2:54, na.rm = FALSE)

# Print stomach_cancer_death_female_year_as_row
# stomach_cancer_death_female_year_as_row

# Change stomach cancer death's value as numberic 
as.numeric(stomach_cancer_death_female_year_as_row$Stomach_Cancer_Death_Female)

# Show the mean of stomach cancer deaths per 100,000 female of each country from 1950 to 2002
paste("The Mean of Stomach Cancer Deaths Per 100,000 Female By Country from 1950 to 2002")
stomach_cancer_death_female_year_as_row %>% 
  group_by(Country) %>% 
  summarise(mean=mean(Stomach_Cancer_Death_Female, na.rm = TRUE), count=sum(!is.na(Stomach_Cancer_Death_Female))) %>%
  arrange(desc(mean))

```

```{r}

# Join stomach_cancer_death_male_year_as_row and stomach_cancer_death_female_year_as_row
stomach_cancer_death_year_as_row <- inner_join(stomach_cancer_death_male_year_as_row, stomach_cancer_death_female_year_as_row)

# Add stomach cancer death numbers for male and female, create new column, and store the values in stomach_cancer_death_year_as_row
stomach_cancer_death_year_as_row <- stomach_cancer_death_year_as_row %>% 
  mutate(Stomach_Cancer_Death = Stomach_Cancer_Death_Male + Stomach_Cancer_Death_Female)

# Print stomach_cancer_death_year_as_row
# stomach_cancer_death_year_as_row

# Show the mean of stomach cancer deaths per 100,000 person of each country from 1950 to 2002
paste("The Mean of Stomach Cancer Deaths Per 100,000 Person By Country from 1950 to 2002")
stomach_cancer_death_year_as_row %>% 
  group_by(Country) %>% 
  summarise(mean=mean(Stomach_Cancer_Death, na.rm = TRUE), count=sum(!is.na(Stomach_Cancer_Death))) %>%
  arrange(desc(mean))


```

```{r}

# Show basic descriptive statistics
summary(stomach_cancer_death_year_as_row)

# Standard Deviation of stomach cancer deaths per 100,000 person
ipp_sd <- round(sd(stomach_cancer_death_year_as_row$Stomach_Cancer_Death, na.rm = TRUE), 2)
paste("The Standard Deviation of Stomach Cancer Deaths Per 100,000 Person Is ", ipp_sd, ".")

```

```{r}

# Create tables for different years in order to create histograms

stomach_cancer_death_1987 <- subset(stomach_cancer_death_year_as_row, Year == 1987) 
stomach_cancer_death_1992 <- subset(stomach_cancer_death_year_as_row, Year == 1992) 
stomach_cancer_death_1997 <- subset(stomach_cancer_death_year_as_row, Year == 1997) 
stomach_cancer_death_2002 <- subset(stomach_cancer_death_year_as_row, Year == 2002) 

# Histogram showing stomach cancer deaths in different countries

hist(stomach_cancer_death_1987$Stomach_Cancer_Death, xlab="Stomach Cancer Deaths Per 100,000 Person 1987", main="Stomach Cancer Deaths In Different Countries in 1987")
hist(stomach_cancer_death_1992$Stomach_Cancer_Death, xlab="Stomach Cancer Deaths Per 100,000 Person 1992", main="Stomach Cancer Deaths In Different Countries in 1992")
hist(stomach_cancer_death_1997$Stomach_Cancer_Death, xlab="Stomach Cancer Deaths Per 100,000 Person 1997", main="Stomach Cancer Deaths In Different Countries in 1997")
hist(stomach_cancer_death_2002$Stomach_Cancer_Death, xlab="Stomach Cancer Deaths Per 100,000 Person 2002", main="Stomach Cancer Deaths In Different Countries in 2002")

```

```{r}

# Check whether the outliers are reasonable.
# There is only one outlier that is over 110 deaths. It is not surprising that Iceland has the highest numbers because its stomach cancer death numbers have been high in different years. 

subset(stomach_cancer_death_year_as_row, Stomach_Cancer_Death > 110)


```

```{r}

# Join all "year_as_row"" data frame using full_Join

# Join income_pp_year_as_row and life_expectancy_year_as_row

income_vs_life_expectancy <- full_join(income_pp_year_as_row, life_expectancy_year_as_row)

# Join total_health_spending_pp_year_as_row and government_health_spending_pp_year_as_row

total_n_gov_health_spending <- full_join(total_health_spending_pp_year_as_row, government_health_spending_pp_year_as_row)

# Join income_vs_life_expectancy and total_n_gov_health_spending

income_vs_life_vs_spending <- full_join(income_vs_life_expectancy, total_n_gov_health_spending)


# Join data frames of all types of cancer deaths

breast_cervical_c <- full_join(breast_cancer_death_year_as_row, cervical_cancer_death_year_as_row)

breast_cervical_lung_c <- full_join(breast_cervical_c, lung_cancer_death_year_as_row)

breast_cervical_lung_liver_c <- full_join(breast_cervical_lung_c, liver_cancer_death_year_as_row)

breast_cervical_lung_liver_prostate_c <- full_join(breast_cervical_lung_liver_c, prostate_cancer_death_year_as_row)

breast_cervical_lung_liver_prostate_stomach_c <- full_join(breast_cervical_lung_liver_prostate_c, stomach_cancer_death_year_as_row)

# Join food supply and improved_drinking_water

food_n_water <- full_join(food_supply_year_as_row, improved_drinking_water_year_as_row)

# Join cancer death data frame and income/life expectancy/health spending data frame

all_year_as_row <- full_join(income_vs_life_vs_spending, breast_cervical_lung_liver_prostate_stomach_c)

# Join all_year_as_row and food_n_water

all_year_as_row <- full_join(all_year_as_row, food_n_water)

```

```{r}

# Join income_pp_year_as_row and life_expectancy_year_as_row by inner_join
income_vs_life_expectancy_in <- inner_join(income_pp_year_as_row, life_expectancy_year_as_row)

# Create subsets for income/life data of 1960, 1970, 1980, 1990, 2000, and 2010
income_vs_life_expectancy_in_1960 <- subset(income_vs_life_expectancy_in, Year == 1960) 
income_vs_life_expectancy_in_1970 <- subset(income_vs_life_expectancy_in, Year == 1970) 
income_vs_life_expectancy_in_1980 <- subset(income_vs_life_expectancy_in, Year == 1980) 
income_vs_life_expectancy_in_1990 <- subset(income_vs_life_expectancy_in, Year == 1990) 
income_vs_life_expectancy_in_2000 <- subset(income_vs_life_expectancy_in, Year == 2000) 
income_vs_life_expectancy_in_2010 <- subset(income_vs_life_expectancy_in, Year == 2010) 

# Bind rows in all subsets for income/life data of 1960 and 2010

income_vs_life_expectancy_in_1960n2010 <- bind_rows(income_vs_life_expectancy_in_2010, income_vs_life_expectancy_in_1960)

# Scatterplot 1960 and 2010
ggplot(income_vs_life_expectancy_in_1960n2010, aes(x = Income_per_person, y = Life_Expectancy, col = Year)) + geom_point(size = 3, alpha = 0.3, position = "jitter") + labs(x = "GDP Per Capita (US$)", y = "Life Expectancy (Year)", title = "Income and Life Expectancy by Year") + geom_smooth(method = "lm", se = FALSE, linetype = 2) + scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x))) 

# Bind rows in all subsets for income/life data of 1960, 1970, 1980, 1990, 2000, and 2010

#income_vs_life_expectancy_in_every10yrs <- bind_rows(income_vs_life_expectancy_in_2010, income_vs_life_expectancy_in_2000)

#income_vs_life_expectancy_in_every10yrs <- bind_rows(income_vs_life_expectancy_in_every10yrs, income_vs_life_expectancy_in_1990)

#income_vs_life_expectancy_in_every10yrs <- bind_rows(income_vs_life_expectancy_in_every10yrs, income_vs_life_expectancy_in_1980)

#income_vs_life_expectancy_in_every10yrs <- bind_rows(income_vs_life_expectancy_in_every10yrs, income_vs_life_expectancy_in_1970)

#income_vs_life_expectancy_in_every10yrs <- bind_rows(income_vs_life_expectancy_in_every10yrs, income_vs_life_expectancy_in_1960)


# Scatterplot 1960-2010

# ggplot(income_vs_life_expectancy_in_every10yrs, aes(x = Income_per_person, y = Life_Expectancy, col = Year)) + geom_point(size = 3, alpha = 0.3, position = "jitter") + labs(x = "GDP Per Capita (US$)", y = "Life Expectancy (Year)", title = "Income and Life Expectancy by Year") + geom_smooth(method = "lm", se = FALSE, linetype = 2) + scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x))) 


```

```{r}

# Join life_expectancy_year_as_row, total_health_spending_pp_year_as_row, and government_health_spending_pp_year_as_row by inner_join

life_total_gov_spend_in <- inner_join(life_expectancy_year_as_row, total_health_spending_pp_year_as_row)

life_total_gov_spend_in <- inner_join(life_total_gov_spend_in, government_health_spending_pp_year_as_row)

# Create subsets for data of 1995, 2000, 2005, and 2010
life_total_gov_spend_in_1995 <- subset(life_total_gov_spend_in, Year == 1995) 
life_total_gov_spend_in_2000 <- subset(life_total_gov_spend_in, Year == 2000) 
life_total_gov_spend_in_2005 <- subset(life_total_gov_spend_in, Year == 2005) 
life_total_gov_spend_in_2010 <- subset(life_total_gov_spend_in, Year == 2010) 

# Bind rows in all subsets for data of 1995, 2000, 2005, and 2010

life_total_gov_spend_in_every5yrs <- bind_rows(life_total_gov_spend_in_1995, life_total_gov_spend_in_2000)

life_total_gov_spend_in_every5yrs <- bind_rows(life_total_gov_spend_in_every5yrs, life_total_gov_spend_in_2005)

life_total_gov_spend_in_every5yrs <- bind_rows(life_total_gov_spend_in_every5yrs, life_total_gov_spend_in_2010)

# Scatterplot - total health spending 
ggplot(life_total_gov_spend_in_every5yrs, aes(x = Total_Health_Spending_Per_Person, y = Life_Expectancy, col = Year)) + geom_point(size = 1, alpha = 0.5, position = "jitter") + labs(x = "Total Health Spending Per Person (US$)", y = "Life Expectancy (Year)", title = "Total Health Spending and Life Expectancy by Year") + geom_smooth(method = "lm", se = FALSE, linetype = 2) + scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))

# Scatterplot - government health spending
ggplot(life_total_gov_spend_in_every5yrs, aes(x = Government_Health_Spending_Per_Person, y = Life_Expectancy, col = Year)) + geom_point(size = 1, alpha = 0.5, position = "jitter") + labs(x = "Government Health Spending Per Person (US$)", y = "Life Expectancy (Year)", title = "Government Health Spending and Life Expectancy by Year") + geom_smooth(method = "lm", se = FALSE, linetype = 2) + scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))

# pairs - Income, Life, Total and Government Health Spending
pairs(~log10(Income_per_person)+log10(Life_Expectancy)+log10(Total_Health_Spending_Per_Person)+log10(Government_Health_Spending_Per_Person), data=all_year_as_row)

```

```{r}
# Join life_expectancy_year_as_row and improved_drinking_water_year_as_row by inner_join

life_water_in <- inner_join(life_expectancy_year_as_row, improved_drinking_water_year_as_row)

# Create subsets for data of 1997 and 2007
life_water_in_1997 <- subset(life_water_in, Year == 1997) 
life_water_in_2007 <- subset(life_water_in, Year == 2007) 

# Bind rows in all subsets for data of 1997 and 2007
life_water_in_2yrs <- bind_rows(life_water_in_1997, life_water_in_2007)

# Scatterplot - Improved Drinking Water 
ggplot(life_water_in_2yrs, aes(x = Improved_Water, y = Life_Expectancy, col = Year)) + geom_point(size = 1, alpha = 0.5, position = "jitter") + labs(x = "Percentage of Population Using Improved Drinking Water Sources", y = "Life Expectancy (Year)", title = "Improved Drinking Water Sources and Life Expectancy by Year") + geom_smooth(method = "lm", se = FALSE, linetype = 2) + scale_x_sqrt()
```
```{r}
# Join life_expectancy_year_as_row and food_supply_year_as_row by inner_join

life_food_in <- inner_join(life_expectancy_year_as_row, food_supply_year_as_row)

# Create subsets for data of 1997 and 2007
life_food_in_1997 <- subset(life_food_in, Year == 1997) 
life_food_in_2007 <- subset(life_food_in, Year == 2007) 

# Bind rows in all subsets for data of 1997 and 2007
life_food_in_2yrs <- bind_rows(life_food_in_1997, life_food_in_2007)

# Scatterplot - Food Supply 
ggplot(life_food_in_2yrs, aes(x = Food_Supply, y = Life_Expectancy, col = Year)) + geom_point(size = 1, alpha = 0.5, position = "jitter") + labs(x = "KCal Per Person Per Day", y = "Life Expectancy (Year)", title = "Food Supply and Life Expectancy by Year") + geom_smooth(method = "lm", se = FALSE, linetype = 2) + scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))
```


```{r}

# Create subsets for data of 1987, 1992, 1997, 2002
all_year_as_row_1987 <- subset(all_year_as_row, Year == 1987) 
all_year_as_row_1992 <- subset(all_year_as_row, Year == 1992) 
all_year_as_row_1997 <- subset(all_year_as_row, Year == 1997) 
all_year_as_row_2002 <- subset(all_year_as_row, Year == 2002) 

# Bind rows in all subsets for data of 1987, 1992, 1997, 2002

life_cancer_every5yrs <- bind_rows(all_year_as_row_1987, all_year_as_row_1992)

life_cancer_every5yrs <- bind_rows(life_cancer_every5yrs, all_year_as_row_1997)

life_cancer_every5yrs <- bind_rows(life_cancer_every5yrs, all_year_as_row_2002)

# Calculate the total of different cancer deaths in 2010 and create a new column for the total (for creating plot for total cancer deaths)

total_cancer_death_2002 <- all_year_as_row_2002 %>% 
  mutate(All_Cancer_Death = Breast_Cancer_Death + Cervical_Cancer_Death + Liver_Cancer_Death + Lung_Cancer_Death + Stomach_Cancer_Death + Prostate_Cancer_Death)

# Create new data frame which has values of different cancer death in rows rather than columns (for creating plot for different cancer deaths in 2002)

all_cancer_as_row_2002 <- select(all_year_as_row_2002, Country, Year, Income_per_person, Life_Expectancy, Total_Health_Spending_Per_Person, Government_Health_Spending_Per_Person, Breast_Cancer_Death, Cervical_Cancer_Death, Lung_Cancer_Death, Liver_Cancer_Death, Prostate_Cancer_Death, Stomach_Cancer_Death)

all_cancer_as_row_2002 <- gather(all_cancer_as_row_2002, "Cancer", "Death", 7:12, na.rm = FALSE)

# Scatterplot - Total cancer death per 100000 person
ggplot(total_cancer_death_2002, aes(x = All_Cancer_Death, y = Life_Expectancy)) + geom_point(size = 3, alpha = 0.5, position = "jitter") + labs(x = "All Cancer Deaths Per 100,000 Person", y = "Life Expectancy (Year)", title = "All Cancer Death and Life Expectancy in 2002") + geom_smooth(method = "lm", se = FALSE, linetype = 2) + scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))

# Scatterplot - Different Types of cancer deaths per 100000 person
ggplot(all_cancer_as_row_2002, aes(x = Death, y = Life_Expectancy, col = Cancer)) + geom_point(size = 1, alpha = 0.3, position = "jitter") + labs(x = "Cancer Deaths Per 100,000 Person", y = "Life Expectancy (Year)", title = "Different Types of Cancer Death and Life Expectancy in 2002") + geom_smooth(method = "lm", se = FALSE, linetype = 2) + scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))

# Scatterplot - Breast cancer deaths per 100000 person 
ggplot(life_cancer_every5yrs, aes(x = Breast_Cancer_Death, y = Life_Expectancy, col = Year)) + geom_point(size = 1, alpha = 0.5, position = "jitter") + labs(x = "Breast Cancer Deaths Per 100,000 Person", y = "Life Expectancy (Year)", title = "Breast Cancer Death and Life Expectancy by Year") + geom_smooth(method = "lm", se = FALSE, linetype = 2) + scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))

# Scatterplot - Cervical cancer deaths per 100000 person
ggplot(life_cancer_every5yrs, aes(x = Cervical_Cancer_Death, y = Life_Expectancy, col = Year)) + geom_point(size = 1, alpha = 0.5, position = "jitter") + labs(x = "Cervical Cancer Deaths Per 100,000 Person", y = "Life Expectancy (Year)", title = "Cervical Cancer Death and Life Expectancy by Year") + geom_smooth(method = "lm", se = FALSE, linetype = 2) + geom_smooth(method = "lm", se = FALSE, linetype = 2) + scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))

# Scatterplot - Liver cancer deaths per 100000 person
ggplot(life_cancer_every5yrs, aes(x = Liver_Cancer_Death, y = Life_Expectancy, col = Year)) + geom_point(size = 1, alpha = 0.5, position = "jitter") + labs(x = "Liver Cancer Deaths Per 100,000 Person", y = "Life Expectancy (Year)", title = "Liver Cancer Death and Life Expectancy by Year") + geom_smooth(method = "lm", se = FALSE, linetype = 2) + scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))

# Scatterplot - Lung cancer deaths per 100000 person 
ggplot(life_cancer_every5yrs, aes(x = Lung_Cancer_Death, y = Life_Expectancy, col = Year)) + geom_point(size = 1, alpha = 0.5, position = "jitter") + labs(x = "Lung Cancer Deaths Per 100,000 Person", y = "Life Expectancy (Year)", title = "Lung Cancer Death and Life Expectancy by Year") + geom_smooth(method = "lm", se = FALSE, linetype = 2) + scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))

# Scatterplot - Prostate cancer deaths per 100000 person 
ggplot(life_cancer_every5yrs, aes(x = Prostate_Cancer_Death, y = Life_Expectancy, col = Year)) + geom_point(size = 1, alpha = 0.5, position = "jitter") + labs(x = "Prostate Cancer Deaths Per 100,000 Person", y = "Life Expectancy (Year)", title = "Prostate Cancer Death and Life Expectancy by Year") + geom_smooth(method = "lm", se = FALSE, linetype = 2) + scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))

# Scatterplot - Stomach cancer deaths per 100000 person 
ggplot(life_cancer_every5yrs, aes(x = Stomach_Cancer_Death, y = Life_Expectancy, col = Year)) + geom_point(size = 1, alpha = 0.5, position = "jitter") + labs(x = "Stomach Cancer Deaths Per 100,000 Person", y = "Life Expectancy (Year)", title = "Stomach Cancer Death and Life Expectancy by Year") + geom_smooth(method = "lm", se = FALSE, linetype = 2) + scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))


```


```{r}

# Save the cleaned file as .csv

write.csv(all_year_as_row, "income_life_spend_cancer_full_join.csv", row.names = FALSE)

```
