---
title: "Capstone Project Proposal"
author: "H Karen Tam"
date: "October 16, 2017" 
output: html_document
---

Update: 12/13/2017

#### Dataset:

*	The dataset shows income per person and life expectancy by country. Health expenditure, death rates of different types of cancer, food supply, and clean drinking water sources are included as well. 

*	URL: http://www.gapminder.org/data/

* Variables and Links to Data: 

    + About 170 countries

    + Life Expectancy (1960-2016)	
        + http://docs.google.com/spreadsheet/pub?key=tiAiXcrneZrUnnJ9dBU-PAw&output=xlsx

    + GDP per capita (1960-2011)
        + http://docs.google.com/spreadsheet/pub?key=0AkBd6lyS3EmpdHo5S0J6ekhVOF9QaVhod05QSGV4T3c&output=xlsx

    + Per capita total expenditure on health at average exchange rate (1995-2010)
        + http://docs.google.com/spreadsheet/pub?key=pyj6tScZqmEeL79qOoKtofQ&output=xlsx 

    +	Per capita government expenditure on health at average exchange rate (1995-2010)
        + http://docs.google.com/spreadsheet/pub?key=tBwBBkViOJoycBhLnWHqwSQ&output=xlsx 

    +	Out-of-pocket expenditure as percentage of total health expenditure (1995-2010)
        + http://docs.google.com/spreadsheet/pub?key=tXf6_OUYVmyEMZo0g4DQw6w&output=xlsx 

    +	Breast cancer deaths per 100,000 female (1950-2002) 
        + http://docs.google.com/spreadsheet/pub?key=phAwcNAVuyj3wJUwXXDdiGg&output=xlsx

    +	Cervical cancer deaths per 100,000 women (1950-2002) 
        + http://docs.google.com/spreadsheet/pub?key=phAwcNAVuyj0jPl21g3mqfQ&output=xlsx
    
    +	Liver cancer deaths per 100,000 male (1950-2002) 
        + http://docs.google.com/spreadsheet/pub?key=phAwcNAVuyj3rojF8TmZtOw&output=xlsx

    +	Liver cancer deaths per 100,000 female (1955-2002) 
        + http://docs.google.com/spreadsheet/pub?key=phAwcNAVuyj2ItBsVpK9VBA&output=xlsx

    +	Lung cancer deaths per 100,000 male (1950-2002) 
        + http://docs.google.com/spreadsheet/pub?key=phAwcNAVuyj2_ibAjsuNgYA&output=xlsx

    +	Lung cancer deaths per 100,000 female (1950-2002) 
        + http://docs.google.com/spreadsheet/pub?key=phAwcNAVuyj2hZorcv6aVLA&output=xlsx

    +	Prostate cancer deaths per 100,000 male (1950-2002) 
        + http://docs.google.com/spreadsheet/pub?key=phAwcNAVuyj2S9phBhTP3dw&output=xlsx

    +	Stomach cancer deaths per 100,000 male (1950-2002) 
        + http://docs.google.com/spreadsheet/pub?key=phAwcNAVuyj3ky4_oAkatBw&output=xlsx 

    +	Stomach cancer deaths per 100,000 female (1950-2002)
        + http://docs.google.com/spreadsheet/pub?key=phAwcNAVuyj0RpUEQPgGcZQ&output=xlsx 

    + Food supply - Kilocalories available, on average, for each person, each day (1961-2007)
        + http://docs.google.com/spreadsheet/pub?key=0ArfEDsV3bBwCdGlYVVpXX20tbU13STZyVG0yNkRrZnc&output=xlsx
        
    + Proportion of the population using improved drinking water sources (1991-2010)
        + http://docs.google.com/spreadsheet/pub?key=pyj6tScZqmEd98lRwrU3gIg&output=xlsx


#### What is the problem I want to solve?

* Through this dataset, I would like to know whether poor people live shorter from the global perspective?

* Does total health expenditure and government’s health expenditure help citizens live longer? 

* Do cancers contriute to the shorter average life expectancy of the country? What kinds of cancer contribute more to shorter life expectancy?  I would like to look at common cancers including breast cancer, cervical cancer, lung cancer, stomach cancer, liver cancer, and prostate cancer. 

* Do food supply and clean water contribute to longer life expectancy?


#### Who is my client and why do they care about this problem? In other words, what will my client DO or DECIDE based on my analysis that they wouldn’t have otherwise?

*	Government agencies, public health organizations, healthcare facilities, and medical professionals would be interested to know relationships between poverty, life expectancy, cancer rate, in order to improve income inequality problem in terms of longevity and cancer rate in their countries, regions, and communities.


#### What data am I going to use for this? How will I acquire this data?

*	I am going to use data provided by Gapminder at http://www.gapminder.org/data/. 

* To search data related to my questions, I use keywords including life expectancy, income, health expenditure, death, cancer, food, and water.

* The project will focus on studying relationships between citizen's life expectancy of the countries and variables including income, health expenditure, cancer deaths, food supply, and clean drinking water sources. 

#### In brief, outline your approach to solving this problem (knowing that this might be changed later.)

I would like to see how good income, health spending, cancer death, food supply, and clean drinking water can predict life expectancy. Therefore, I will use Multiple Linear Regression to test how change in predictor variables predict the level of change in life expectancy. In the meantime, Pearson's correlation will be used to check the correlation between predictor variables because high correlation between predictor variables suggests that the effects on life expectancy are somewhat bounded together. 

Data visualization and descriptive statistics are performed as well for preliminary exploration of the data.  

#### What are your deliverables? 

R code, final paper, and a slide deck will be posted in github repository and will be delivered through a blog post. 



