---
title: "Capstone Project Data Wrangling v1"
author: "H Karen Tam"
date: "October 26, 2017"
output: html_document
---

```{r, echo=FALSE}

# Load tidyr
suppressMessages(library(tidyr))

# Load dplyr
suppressMessages(library(dplyr))

# Load readxl - read excel files
library(readxl)

# Load ggplot2
suppressMessages(library(ggplot2))

```

# Apply Data Wrangling to Capstone Project


## 1. Add your cleaned-up data set to the github repository for your project.

My cleaned up csv file: 

https://github.com/karentam/capstoneproject1/blob/master/income_life_spend_cancer_full_join.csv


## 2. Summarize the most important steps you took in cleaning up your data in a short document. 

### Reshape the data for making plots and descriptive statistics

I use gather() in tidyr package to gather year columns into key-value pairs. The restructured data frame is easier to do scatter plots, histograms, and descriptive statistics based on countries and years. 

### Join the data from different data frames

I use full_join () and inner_join() in dplyr package to join all variables together into a data frame. I also obtain total numbers of lung, liver, and stomach cancer deaths for each country in different years by adding numbers of male and female, and enter these numbers into the data frame. It is easier to make scatter plots and show relationships between income and life expectancy, life expectancy and health spending, as well as life expectancy and various cancer deaths.

### Examine Outliers

I run summary statistics, make histograms and subsets to identify outliers for each variable. Outliers are examined and are reasonable with the countries' situations in specific years. For example, very short life expectancy numbers are appeared due to wars and natural disasters in specific countries and in specific time period. It is the fact that a few countries may have very high cancer deaths of a particular type of cancer. 

Different kinds of cancer deaths and life expectancy are normally distributed. It is expected that income and health spending have more outliers because some countries are wealthier than other countries. 

My code to perform the above works: 

https://github.com/karentam/capstoneproject1/blob/master/Capstone_project_v1.Rmd


## 3. Data Visualization 

### Scatter Plots, Density Plots, and Histograms

https://github.com/karentam/capstoneproject1/blob/master/Capstone_project_data_visualization_v1.Rmd











